plugins:
  - jest
env:
  es2021: true
  node: true
  jest: true
extends: 
- 'airbnb-base'
- 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 0
  import/no-duplicates: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант